system:
  hostname: sobey-1
  user:
    name: user-test
    passwd: user-test
  network:
    name:
    macAddr: 00:AA:BB:04:03:02
    ipAddr: 192.168.206.137
    netmask: 255.255.255.0
    gateway: 192.168.206.2
    dns1:
    dns2:
