system:
  hostname: sobey-1
  user:
    name: user-test
    passwd: user-test
  network:
    name: ens33
    macAddr: 00:AA:BB:CC:DD:FF
    ipAddr: 192.168.206.136
    netmask: 255.255.255.0
    gateway: 192.168.206.2
    dns1: 192.168.206.2
    dns2:
